version: '3.7' #1

services: #2
  my-first-api: #3
    build: .   #4
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"] #5
    volumes: #6
      - .:/code #7
    ports:  #8
      - "8000:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
          # cpus: '1'
          # memory: 2048M
    # reservations:
    #   cpus: '0.0001'
    #   memory: 20M
# More
# resources:
#   limits:
#     cpus: '0.1'
#     memory: 512M

  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=root
  #     - POSTGRES_DB=postgres_db
